CREATE TABLE FactBatch
(QuantityProduced INT,
QualityRating INT,
StartDate INT,
EstimatedEndTime INT,
ActualEndTime INT,
ShippingDate INT,
ProoductionCost INT,
ShippingCost INT,
QuantityShipped INT,
OrderQuantity INT,
OrderSalePrice INT,
Order_SK INT,
Complience_SK INT,
Factory_SK INT,
Item_SK INT,
Shipment_SK INT,
Date_SK INT,
CONSTRAINT pk_FactBatch PRIMARY KEY (Order_SK, Complience_SK, Factory_SK, Item_SK, Shipment_SK, Date_SK)
);